site_name: Documentação GIMI
repo_url: https://github.com/Eduardo-Milagres/documentacao_gimi
repo_name: documentacao_gimi
edit_uri: tree/main/docs

theme: 
  name: material
  language: pt-BR
markdown_extensions:
  - admonition
  - nl2br
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji  # Suporte a emojis
  - pymdownx.tasklist  # Suporte para tarefas
  - pymdownx.mark  # Suporte para marcações
  - pymdownx.tilde  # Suporte a tachado
  - pymdownx.highlight  # Suporte a código
plugins:
  - macros
  - search
  - callouts

extra:
  nomes:
    github_doc_repo: documentacao_gimi
    perfil_viga: perfil U 
  links:
    markdown: "https://www.markdownguide.org/"
    material: "https://squidfunk.github.io/mkdocs-material/"
    mkdocs: "https://www.mkdocs.org/"
    mkdocs_instalacao: "https://www.mkdocs.org/user-guide/installation/"
    python: "https://www.python.org/"
    python_download: "https://www.python.org/downloads/"
    github: "https://github.com/"
    github_doc_repo: "https://github.com/Eduardo-Milagres/documentacao_gimi"
    netlify: "https://app.netlify.com/"
    netlify_doc_link: "https://documentacaogimi.netlify.app/"
  imagens:
    python_instalacao: "![Instalação python](/assets/images/instalacao_python.PNG)"